name: Deploy Plugin

on:
  push:
    tags:
      - '*.*.*'

jobs:

  tags-check:
    name: Check tagged branch
    if: contains(github.ref, 'tags/')
    uses: tarosky/workflows/.github/workflows/check-tag-in-branch.yml@main
    with:
      allowed_branch: "main"

  release:
    name: Create Release
    needs: tags-check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress

      - name: Build
        run: |
          PREFIX="refs/tags/"
          VERSION=${GITHUB_REF#"$PREFIX"}
          echo "Building v${VERSION}..."
          sed -i "s/Version: .*/Version: ${VERSION}/g" ./boswell.php
          curl -L https://raw.githubusercontent.com/fumikito/wp-readme/master/wp-readme.php | php
          sed -i "s/^Stable Tag: .*/Stable Tag: ${VERSION}/g" ./readme.txt

      - name: Zip Archive
        run: |
          REPO=${{ github.event.repository.name }}
          mkdir "${REPO}"
          rsync -av --exclude="${REPO}" --exclude=.git --exclude-from=.distignore ./ "./${REPO}/"
          zip -r "./${REPO}.zip" "./${REPO}"

      - name: Upload release asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          gh release upload "${TAG}" "${{ github.event.repository.name }}.zip" --clobber
